-- Segunda tanda de etiquetas de match (public.tags, administrado_por_admin=true):
-- materiales, capacidades/servicios, industrias, necesidades y modalidades, para
-- que el catálogo quede bien completo. Idempotente (ON CONFLICT DO NOTHING).

insert into public.tags (nombre, slug, tipo_tag, administrado_por_admin, activo)
values
  -- ── Materiales ──
  ('Chapa galvanizada', 'chapa-galvanizada', 'material', true, true),
  ('Acero SAE 1045', 'acero-sae-1045', 'material', true, true),
  ('Acero 4140', 'acero-4140', 'material', true, true),
  ('Inoxidable 304', 'inoxidable-304', 'material', true, true),
  ('Inoxidable 316', 'inoxidable-316', 'material', true, true),
  ('Aluminio anodizado', 'aluminio-anodizado', 'material', true, true),
  ('Bronce fosforoso', 'bronce-fosforoso', 'material', true, true),
  ('Silicona', 'silicona', 'material', true, true),
  ('Neopreno', 'neopreno', 'material', true, true),
  ('EVA', 'eva', 'material', true, true),
  ('Poliestireno expandido (EPS)', 'poliestireno-expandido-eps', 'material', true, true),
  ('Policarbonato', 'policarbonato', 'material', true, true),
  ('Polietileno de alta densidad (HDPE)', 'polietileno-alta-densidad-hdpe', 'material', true, true),
  ('Poliamida', 'poliamida', 'material', true, true),
  ('Melamina', 'melamina', 'material', true, true),
  ('Aglomerado', 'aglomerado', 'material', true, true),
  ('Terciado', 'terciado', 'material', true, true),
  ('Yeso', 'yeso', 'material', true, true),
  ('Grafito', 'grafito', 'material', true, true),
  ('Fieltro', 'fieltro', 'material', true, true),
  ('Corcho', 'corcho', 'material', true, true),
  ('Lona', 'lona', 'material', true, true),
  -- ── Capacidades / servicios ──
  ('Corte por chorro de agua', 'corte-por-chorro-de-agua', 'capacidad', true, true),
  ('Punzonado CNC', 'punzonado-cnc', 'capacidad', true, true),
  ('Plegado CNC', 'plegado-cnc', 'capacidad', true, true),
  ('Roscado', 'roscado', 'capacidad', true, true),
  ('Bruñido', 'brunido', 'capacidad', true, true),
  ('Lapidado', 'lapidado', 'capacidad', true, true),
  ('Metalizado', 'metalizado', 'capacidad', true, true),
  ('Pintura en polvo', 'pintura-en-polvo', 'capacidad', true, true),
  ('Zincado', 'zincado', 'capacidad', true, true),
  ('Fosfatizado', 'fosfatizado', 'capacidad', true, true),
  ('Pavonado', 'pavonado', 'capacidad', true, true),
  ('Vulcanizado', 'vulcanizado', 'capacidad', true, true),
  ('Rotomoldeo', 'rotomoldeo', 'capacidad', true, true),
  ('Calandrado', 'calandrado', 'capacidad', true, true),
  ('Laminado', 'laminado', 'capacidad', true, true),
  ('Guillotinado', 'guillotinado', 'capacidad', true, true),
  ('Grabado láser', 'grabado-laser', 'capacidad', true, true),
  ('Ploteo de corte', 'ploteo-de-corte', 'capacidad', true, true),
  ('Ruteado CNC', 'ruteado-cnc', 'capacidad', true, true),
  ('Sublimación', 'sublimacion', 'capacidad', true, true),
  ('Tampografía', 'tampografia', 'capacidad', true, true),
  ('Encuadernación', 'encuadernacion', 'capacidad', true, true),
  ('Bobinado de motores', 'bobinado-de-motores', 'capacidad', true, true),
  ('Rebobinado de motores', 'rebobinado-de-motores', 'capacidad', true, true),
  ('Electroerosión', 'electroerosion', 'capacidad', true, true),
  ('Fresado 5 ejes', 'fresado-5-ejes', 'capacidad', true, true),
  ('Torneado vertical', 'torneado-vertical', 'capacidad', true, true),
  ('Soldadura por punto', 'soldadura-por-punto', 'capacidad', true, true),
  ('Soldadura robotizada', 'soldadura-robotizada', 'capacidad', true, true),
  ('Montaje SMD', 'montaje-smd', 'capacidad', true, true),
  ('Cableado industrial', 'cableado-industrial', 'capacidad', true, true),
  -- ── Industrias / rubros ──
  ('Autopartista', 'autopartista', 'industria', true, true),
  ('Electrodomésticos', 'electrodomesticos', 'industria', true, true),
  ('Ferretería industrial', 'ferreteria-industrial', 'industria', true, true),
  ('Molinería', 'molineria', 'industria', true, true),
  ('Panificación', 'panificacion', 'industria', true, true),
  ('Aserradero', 'aserradero', 'industria', true, true),
  ('Marroquinería', 'marroquineria', 'industria', true, true),
  ('Fabricación de maquinaria', 'fabricacion-de-maquinaria', 'industria', true, true),
  ('Estructuras metálicas', 'estructuras-metalicas', 'industria', true, true),
  ('Recipientes a presión', 'recipientes-a-presion', 'industria', true, true),
  ('Muebles metálicos', 'muebles-metalicos', 'industria', true, true),
  ('Iluminación', 'iluminacion', 'industria', true, true),
  ('Electromedicina', 'electromedicina', 'industria', true, true),
  ('Automatización industrial', 'automatizacion-industrial', 'industria', true, true),
  ('Robótica industrial', 'robotica-industrial', 'industria', true, true),
  ('Ascensores y elevadores', 'ascensores-y-elevadores', 'industria', true, true),
  ('Aberturas de aluminio', 'aberturas-de-aluminio', 'industria', true, true),
  ('Herrería', 'herreria', 'industria', true, true),
  -- ── Necesidad que resuelvo ──
  ('Desarrollo de producto', 'desarrollo-de-producto', 'problema', true, true),
  ('Prototipado', 'prototipado', 'problema', true, true),
  ('Ingeniería a medida', 'ingenieria-a-medida', 'problema', true, true),
  ('Puesta a punto', 'puesta-a-punto', 'problema', true, true),
  ('Relevamiento técnico', 'relevamiento-tecnico', 'problema', true, true),
  ('Ensayo de materiales', 'ensayo-de-materiales', 'problema', true, true),
  ('Terciarización de producción', 'terciarizacion-de-produccion', 'problema', true, true),
  ('Consultoría técnica', 'consultoria-tecnica', 'problema', true, true),
  ('Diseño industrial', 'diseno-industrial', 'problema', true, true),
  ('Asesoramiento normativo', 'asesoramiento-normativo', 'problema', true, true),
  ('Gestión de compras', 'gestion-de-compras', 'problema', true, true),
  ('Logística inversa', 'logistica-inversa', 'problema', true, true),
  ('Reparación de emergencia', 'reparacion-de-emergencia', 'problema', true, true),
  ('Repuestos a medida', 'repuestos-a-medida', 'problema', true, true),
  ('Stock permanente', 'stock-permanente', 'problema', true, true),
  -- ── Modalidad de servicio ──
  ('Bajo pedido', 'bajo-pedido', 'modalidad_servicio', true, true),
  ('Producción en serie', 'produccion-en-serie', 'modalidad_servicio', true, true),
  ('Just in time', 'just-in-time', 'modalidad_servicio', true, true),
  ('Exportación', 'exportacion', 'modalidad_servicio', true, true),
  ('Entrega inmediata', 'entrega-inmediata', 'modalidad_servicio', true, true),
  ('Cuenta corriente', 'cuenta-corriente', 'modalidad_servicio', true, true),
  ('Financiación', 'financiacion', 'modalidad_servicio', true, true),
  ('Garantía extendida', 'garantia-extendida', 'modalidad_servicio', true, true),
  ('Servicio post-venta', 'servicio-post-venta', 'modalidad_servicio', true, true),
  ('Cobertura nacional', 'cobertura-nacional', 'modalidad_servicio', true, true)
on conflict do nothing;
